name: Simple Job Example with Boolean

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: true
        default: 'default_value2'
      run_extra:
        description: 'Run additional step?'
        required: true
        default: false
        type: boolean

  push:
    branches:
      - main  # Change this to your desired branch
    inputs:
      input1: 
        default: 'push_value1'
      input2: 
        default: 'push_value2'
      run_extra: 
        default: false

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 || 'default_value1' }}"
          echo "Input 2: ${{ github.event.inputs.input2 || 'default_value2' }}"
          echo "Run extra step: ${{ github.event.inputs.run_extra || false }}"

      - name: Run Extra Step
        # if: ${{ github.event.inputs.run_extra }}
        run: |
          echo "Running the extra step!"
          name: Manual Trigger Workflow
          FILES=$(ls ./)
          echo "Files in directory: $FILES"
          for metric_file_name in $FILES; do
            echo "$metric_file_name"
            metric_name=$(basename "$metric_file_name" .txt)
            echo "$metric_name"
          done
