name: Simple Job Example with Boolean

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: true
        default: 'default_value2'
      run_extra:
        description: 'Run additional step?'
        required: true
        default: false
        type: boolean

  push:
    branches:
      - main  # Change this to your desired branch
    inputs:
      input1: 
        default: 'push_value1'
      input2: 
        default: 'push_value2'
      run_extra: 
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run extra step
        run: |
          echo "Running the extra step!"
          ls 
          pwd
          FILES=$(ls ./)
          echo "Files in directory: $FILES"
          for metric_file_name in $FILES; do
            echo "$metric_file_name"
            metric_name=$(basename "$metric_file_name" .txt)
            echo "$metric_name"
          done
