name: Parallel Jobs Example

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Input for Job 1 and Job 3'
        required: true
        default: 'value1'
        type: string
      param2:
        description: 'Input for Job 2 and Job 4'
        required: true
        default: 'value2'
        type: string
      run_job1:
        description: 'Run Job 1?'
        default: true
        required: false
        type: boolean
      run_job2:
        description: 'Run Job 2?'
        default: true
        required: false
        type: boolean
      run_job3:
        description: 'Run Job 3?'
        default: true
        required: false
        type: boolean
      run_job4:
        description: 'Run Job 4?'
        default: true
        required: false
        type: boolean
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest
    outputs:
      param1: ${{ github.event.inputs.param1 }}
      param2: ${{ github.event.inputs.param2 }}
    steps:
      - name: Print all parameters
        run: |
          echo "Parameters set."
          echo "param1: ${{ github.event.inputs.param1 }}"
          echo "param2: ${{ github.event.inputs.param2 }}"
          echo "run_job1: ${{ github.event.inputs.run_job1 }}"
          echo "run_job2: ${{ github.event.inputs.run_job2 }}"
          echo "run_job3: ${{ github.event.inputs.run_job3 }}"
          echo "run_job4: ${{ github.event.inputs.run_job4 }}"

  job1:
    runs-on: ubuntu-latest
    needs: main-job
    if: ${{ github.event.inputs.run_job1 }}
    steps:
      - name: Run Job 1
        run: |
          echo "Running Job 1 with parameter: ${{ needs.main-job.outputs.param1 }}"

  job2:
    runs-on: ubuntu-latest
    needs: main-job
    if: ${{ github.event.inputs.run_job2 }}
    steps:
      - name: Run Job 2
        run: |
          echo "Running Job 2 with parameter: ${{ needs.main-job.outputs.param2 }}"

  job3:
    runs-on: ubuntu-latest
    needs: main-job
    if: ${{ github.event.inputs.run_job3 }}
    steps:
      - name: Run Job 3
        run: |
          echo "Running Job 3 with parameter: ${{ needs.main-job.outputs.param1 }}"

  job4:
    runs-on: ubuntu-latest
    needs: main-job
    if: ${{ github.event.inputs.run_job4 }}
    steps:
      - name: Run Job 4
        run: |
          echo "Running Job 4 with parameter: ${{ needs.main-job.outputs.param2 }}"
