name: Simple Job Example

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: true
        default: 'default_value2'

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"
